import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { SpotifyTokenProvider } from "@/context/SpotifyTokenContext";

const rubik = Rubik({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black" suppressHydrationWarning>
      <body
        className={`${rubik.className} antialiased bg-black`}
        style={{
          scrollbarColor: "gray black",
          scrollbarWidth: "thin",
        }}
      >
        <SpotifyTokenProvider>
          <div className="md:pb-0 pb-10">
            <Header />
            {children}
          </div>
        </SpotifyTokenProvider>
      </body>
    </html>
  );
}
